export const GET_DATA_FROM_SERVER = 'GET_DATA_FROM_SERVER'

export const GET_FILTER_DATA = 'GET_FILTER_DATA'

export const ADD_PRICE = 'ADD_PRICE'

export const SEARCH_IN_LIST = 'SEARCH_IN_LIST'

export const SEARCH_ACTIVE = 'SEARCH_ACTIVE'

export const CLICK_CATEGORY = 'CLICK_CATEGORY'

export const SELECT_DATA = 'SELECT_DATA'

export const SET_OPEN = 'SET_OPEN'